version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend  # Montuj cały projekt do katalogu /frontend w kontenerze
    environment:
      - NODE_ENV=development
    command: npm start

