version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    volumes:
      - .:/frontend  # Montuj cały projekt do katalogu /frontend w kontenerze
    environment:
      - NODE_ENV=development
    command: npm start

